name: Release-Helper

# Run this workflow every time a new commit pushed to your repository
on:
  workflow_dispatch:
    inputs:
      maxCommitPages:
        description: 'Maximum number of pages to traverse: a safety measure in case there is infinite looping somehow. Each page is 100 commits'
        required: false
        default: '5'

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  release-helper:
    # Name the Job
    name: List all merge commits since last release
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # Runs the Release-Helper action
      - name: Run Release-Helper
        run: |
          python release_helper.py
        env:
          MAX_COMMIT_PAGES: ${{ github.event.inputs.maxCommitPages }}
          REPOSITORY: ${{ github.event.repository.name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}